name: cilp
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.7
  - cython
  - conda>=4.7
  - ipython
  - ipdb
  - numpy
  - scipy
  - pandas
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - pyyaml
  - scikit-learn
  - scikit-optimize
  - tqdm
  - matplotlib
  - psutil
  - hyperopt
  - pytest
  - pytest-cov
  - setproctitle
  - tabulate
  - mlflow
  - pip:
      - tensorflow
      - tensorboardX
      - ray[all]
      # - https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp37-cp37m-manylinux1_x86_64.whl
      - gputil
      - ax-platform
